AI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('model.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

model/urls.py
from django.urls import path
from . import views

app_name='model'
urlpatterns = [
    path('', views.home, name='home'),
    path('result/', views.result, name='result')
]

model/models.py
from django.db import models

# Create your models here.

model/views.py
from django.shortcuts import render
import joblib
import pandas as pd
import numpy as np


def home(request):
    context={}
    return render(request, 'model/home.html', context=context)
    
    
def result(request):
    model=joblib.load('utils/logistic_model.pkl')
    feature_col = ['Property_Area','Education', 'Dependents']
    train_features = ['Credit_History', 'Education', 'Gender']
    
    Data=request.POST
    data=np.array([list(dict(Data).values())[1:]]).reshape(1,-1)
    col=list(dict(Data).keys())[1:]
    loan_test = pd.DataFrame(data, columns=col)
    
    loan_test.Gender = loan_test.Gender.replace({"Male": 1, "Female" : 0})
    loan_test.Married = loan_test.Married.replace({"Yes": 1, "No" : 0})
    loan_test.Self_Employed = loan_test.Self_Employed.replace({"Yes": 1, "No" : 0})
    
    
    le = joblib.load('utils/logistic_label_encoder.pkl')
    for col in feature_col:
        loan_test[col] = le.fit_transform(loan_test[col])
        
    x_test = loan_test[train_features].values
    predicted = model.predict(x_test)
    
    status=['Satisfied' if i==1  else 'Rejected' for i in predicted]
    
    context={'condition': status[0]}
    return render(request, 'model/result.html', context=context)

templates/model/home.html
{% extends 'model/index.html' %}
{% load static %}

{%block title%}

Home

{% endblock %}


{% block body %}

<form class='tm-bg-white-transparent' action='{% url 'model:result' %}' method='POST'>
<div class='justify-content-center align-items-center'>
{% csrf_token %}
	<div class="form-row">
		<div class="col form-group">
		<label for="Loan_ID">Loan ID:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Loan_ID" name="Loan_ID"><br>
		</div>
		<div class="col form-group">
		<label for="Gender">Gender:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Gender" name="Gender"><br>
		</div>
	</div>
	
	<div class="form-row">
	
		<div class="col form-group">
		<label for="Married">Married:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Married" name="Married"><br>
		</div>
		<div class="col form-group">
		<label for="Dependents">Dependents:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Dependents" name="Dependents"><br>
		</div>
	</div>
	
	<div class="form-row">
		
		<div class="col form-group">
		<label for="Education">Education:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Education" name="Education"><br>
		</div>
		<div class="col form-group">
		<label for="Self_Employed">Self Employed:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Self_Employed" name="Self_Employed"><br>
		</div>
	</div>
	
	<div class="form-row">
		
		<div class="col form-group">
		<label for="ApplicantIncome">Applicant Income:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="ApplicantIncome" name="ApplicantIncome"><br>
		</div>
		<div class="col form-group">
		<label for="CoapplicantIncome">Coapplicant Income:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="CoapplicantIncome" name="CoapplicantIncome"><br>
		</div>
	</div>
	
	<div class="form-row">
	
		<div class="col form-group">
		<label for="LoanAmount">Loan Amount:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="LoanAmount" name="LoanAmount"><br>
		</div>
		<div class="col form-group">
		<label for="Loan_Amount_Term">Loan Amount Term:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Loan_Amount_Term" name="Loan_Amount_Term"><br>
		</div>
	</div>
	
	<div class="form-row">
	
		<div class="col form-group">
		<label for="Credit_History">Credit History:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Credit_History" name="Credit_History"><br>
		</div>
		<div class="col form-group">
		<label for="Property_Area">Property Area:</label><br>
		<input class="form-control rounded-0 border-top-0 border-right-0 border-left-0" type="text" id="Property_Area" name="Property_Area"><br><br>
		</div>
	</div>
	
	<input  type="submit" class="btn btn-primary" value="Submit"><br><br><br>
	
</div>
</form>

{% endblock %}

templates/model/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <link rel="stylesheet" href="{% static 'model/css/all.min.css' %}" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'model/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'model/css/templatemo-style.css' %}" />
    <title>AI | {% block title %}Home{% endblock %}</title>
    
<!--
Mini Profile Template
https://templatemo.com/tm-530-mini-profile
-->
  </head>
  <body>
    <!-- Welcome Section -->
    <section id="tmWelcome" class="parallax-window" data-parallax="scroll" data-image-src="{% static 'model/img/mini-profile-bg-01.jpg' %}">
      <div class="container-fluid tm-brand-container-outer">
        <div class="row">
          <div class="col-12">
            <!-- Logo Area -->
            <!-- Black transparent bg -->
            <div class="ml-auto mr-0 tm-bg-black-transparent text-white tm-brand-container-inner">
              <div class="tm-brand-container text-center">
                <h1 class="tm-brand-name">Mini Profile</h1>
                <p class="tm-brand-description mb-0">simple parallax template</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="tm-bg-white-transparent tm-welcome-container">
        <div class="container-fluid">
          <div class="row h-100">
            <!-- Welcome Text -->
            <!-- White transparent bg -->
            <div class="col-md-7 tm-welcome-left-col">
              <div class="tm-welcome-left">
                <h2 class="tm-welcome-title">Welcome to Mini Profile Page</h2>
                <p class="pb-0">
                  This is Bootstrap v4.3.1 parallax layout for you. Credit goes to <a rel="nofollow" href="https://www.pexels.com">Pexels</a> for 2 background images. In
                  odio sapien, commodo id ullamcorper ac, dignissim at sapien.
                  Nullam leo massa, vaius ac massa et, tincidunt imperdiet
                turpis. </p>
              </div>
            </div>
            <!-- Brown bg -->
            <div class="col-md-5">
              <div class="tm-welcome-right">
                <i class="fas fa-4x fa-address-card p-3 tm-welcome-icon"></i>
                <p class="mb-0">
                  Please spread a word about templatemo website. Anyone can download free Bootstrap CSS templates.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Welcome section -->

    <!-- Portfolio section -->
    <section id="tmPortfolio">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            
			{% block body %}
			
			
			{% endblock %}
			
          </div>
        </div>
      </div>
    </section>
    <!-- End portfolio section -->

    <!-- Contact section -->
    <div id="tmContact" class="parallax-window" data-parallax="scroll" data-image-src="{% static 'model/img/mini-profile-bg-02.jpg' %}">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="tm-contact-items-container">
              <div class="tm-contact-item">
                <i class="fas fa-5x fa-briefcase tm-contact-item-icon"></i>
                <p class="mb-0">
                  Quisque venenatis viverra ultrices. Lorem ipsum dolor sit
                  amet. Nullam sit amet tempor nisl.
                </p>
              </div>
              <div class="tm-contact-item">
                <i class="fas fa-5x fa-building tm-contact-item-icon"></i>
                <p class="mb-0">
                  You can absolutely feel free to use Mini Profile for your web page or any usage for your website.
                </p>
              </div>

              <div class="tm-contact-item">
                <i class="fas fa-5x fa-balance-scale tm-contact-item-icon"></i>
                <p class="mb-0">
                  You are NOT allowed to re-distribute this template in any download website. Else, it is illegal action.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            <form
              action="index.html"
              method="POST"
              id="tmContactForm"
              class="tm-bg-white-transparent"
            >
              <div class="form-group">
                <input
                  type="text"
                  id="contact_name"
                  name="contact_name"
                  class="form-control rounded-0 border-top-0 border-right-0 border-left-0"
                  placeholder="Name"
                  required
                />
              </div>
              <div class="form-group">
                <input
                  type="email"
                  id="contact_email"
                  name="contact_email"
                  class="form-control rounded-0 border-top-0 border-right-0 border-left-0"
                  placeholder="Email"
                  required
                />
              </div>
              <div class="form-group">
                <textarea
                  rows="4"
                  id="contact_message"
                  name="contact_message"
                  class="form-control rounded-0 border-top-0 border-right-0 border-left-0"
                  placeholder="Message"
                  required
                ></textarea>
              </div>
              <div class="text-center">
                <button
                  type="submit"
                  class="btn tm-btn-submit rounded-0 text-white"
                >
                  Submit
                </button>
              </div>
            </form>
          </div>
        </div>
        <!-- row -->
        <div class="row">
          <footer class="col-12">
            <p class="text-center tm-copyright-text">
            Copyright 2020 Mini Profile Page 
            
            - Design: Template Mo</p>
          </footer>
        </div>
      </div>
      <!-- container -->
    </div>
    <!-- section -->
    <script src="{% static 'model/js/jquery.min.js' %}"></script>
    <script src="{% static 'model/js/parallax.min.js' %}"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
      function detectMsBrowser() {
        using_ms_browser =
          navigator.appName == "Microsoft Internet Explorer" ||
          (navigator.appName == "Netscape" &&
            navigator.appVersion.indexOf("Edge") > -1) ||
          (navigator.appName == "Netscape" &&
            navigator.appVersion.indexOf("Trident") > -1);

        if (using_ms_browser == true) {
          alert(
            "Please use Chrome or Firefox for the best browsing experience!"
          );
        }
      }
      function setBrandMarginTop() {
        var bottomContainerHeight = $(".tm-welcome-container").height();

        $(".tm-brand-container-outer").css({
          "margin-top": -bottomContainerHeight + "px"
        });
      }

      $(function() {
        setBrandMarginTop();
        detectMsBrowser();

        // Handle window resize event
        $(window).resize(function() {
          setBrandMarginTop();
        });
      });
    </script>
  </body>
</html>

templates/model/result.html
{% extends 'model/index.html' %}
{% load static %}

{%block title%}

Result

{% endblock %}


{% block body %}

<h1>The eligability of this person is {{condition}}.</h1>

{% endblock %}